-- Snowflake SQL Setup for Happiness Survey
-- Run this script in your Snowflake warehouse to initialize the database

-- Create database (if not exists)
CREATE DATABASE IF NOT EXISTS HAPPINESS_DB;

-- Use the database
USE HAPPINESS_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- Create main survey results table
CREATE TABLE IF NOT EXISTS HAPPINESS_SURVEY (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MOOD VARCHAR(50),
    WORKS_AT_AG BOOLEAN,
    HOW_GOT_CODE VARCHAR(500),
    IN_RED_TEAM BOOLEAN,
    TEAM_NAME VARCHAR(100),
    JOB_WISH VARCHAR(2000),
    STRESS_WISH VARCHAR(2000),
    KNOWLEDGE_LAWYER_NEED VARCHAR(2000),
    HAPPINESS_INTEREST BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create analytics view
CREATE VIEW IF NOT EXISTS SURVEY_ANALYTICS AS
SELECT
    DATE(TIMESTAMP) as SURVEY_DATE,
    COUNT(*) as TOTAL_RESPONSES,
    COUNTIF(MOOD = 'Amazing') as AMAZING_COUNT,
    COUNTIF(MOOD = 'Great') as GREAT_COUNT,
    COUNTIF(MOOD = 'Good') as GOOD_COUNT,
    COUNTIF(MOOD = 'Okay') as OKAY_COUNT,
    COUNTIF(MOOD = 'Not Great') as NOT_GREAT_COUNT,
    ROUND(100.0 * (COUNTIF(MOOD IN ('Amazing', 'Great')) / COUNT(*)), 2) as POSITIVE_PERCENTAGE,
    COUNTIF(WORKS_AT_AG = TRUE) as AG_EMPLOYEE_COUNT,
    COUNTIF(IN_RED_TEAM = TRUE) as RED_TEAM_COUNT,
    COUNTIF(HAPPINESS_INTEREST = TRUE) as INTERESTED_IN_HAPPINESS
FROM HAPPINESS_SURVEY
GROUP BY DATE(TIMESTAMP)
ORDER BY SURVEY_DATE DESC;

-- Create team analytics view
CREATE VIEW IF NOT EXISTS TEAM_ANALYTICS AS
SELECT
    TEAM_NAME,
    COUNT(*) as TEAM_RESPONSES,
    COUNT(DISTINCT DATE(TIMESTAMP)) as DAYS_ACTIVE,
    AVG(CASE WHEN MOOD IN ('Amazing', 'Great') THEN 1 ELSE 0 END) as HAPPINESS_SCORE,
    COUNT(CASE WHEN HAPPINESS_INTEREST = TRUE THEN 1 END) as INTERESTED_EMPLOYEES
FROM HAPPINESS_SURVEY
WHERE TEAM_NAME IS NOT NULL
GROUP BY TEAM_NAME
ORDER BY TEAM_RESPONSES DESC;

-- Create mood trends view
CREATE VIEW IF NOT EXISTS MOOD_TRENDS AS
SELECT
    MOOD,
    COUNT(*) as TOTAL_COUNT,
    ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM HAPPINESS_SURVEY), 2) as PERCENTAGE,
    COUNT(CASE WHEN HAPPINESS_INTEREST = TRUE THEN 1 END) as INTERESTED_COUNT
FROM HAPPINESS_SURVEY
GROUP BY MOOD
ORDER BY TOTAL_COUNT DESC;

-- Show table structure
DESCRIBE TABLE HAPPINESS_SURVEY;

-- Show views created
SELECT SCHEMA_NAME, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PUBLIC'
AND TABLE_NAME IN ('HAPPINESS_SURVEY', 'SURVEY_ANALYTICS', 'TEAM_ANALYTICS', 'MOOD_TRENDS');
